name: lordan_v1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+16

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  google_fonts: ^6.2.1
  go_router: ^15.1.1
  intl: 0.20.2
  shared_preferences: ^2.2.2
  #  easy_localization: ^3.0.4

  font_awesome_flutter: ^10.8.0

  # Voice chat dependencies (to be implemented)
  speech_to_text: ^7.3.0
  permission_handler: ^11.3.0
  # Supabase & Auth
  supabase_flutter: ^2.5.7
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  pinput: ^5.0.1  # OTP code input UI0
  # flutter_tts: ^4.0.2
  uuid: ^4.5.1
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.1.0
  url_launcher: ^6.2.2
  intl_phone_number_input: ^0.7.5
  http: ^1.5.0
  audioplayers: ^6.5.1
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_stripe: ^11.5.0
  flutter_tts: 4.0.2
  in_app_purchase: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
   
    - assets/brand_logos/
    - assets/country_flags/
    - .env
