name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ✅ Ensures full repo is checked out, including ios/Runner.xcodeproj files

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Verify iOS project files
        run: ls -R ios   # ✅ Debug: lists all iOS files so you can confirm Runner.xcodeproj exists

      - name: Build unsigned IPA
        run: flutter build ipa --no-codesign

      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/ipa/*.ipa
